### ISSUE TITLE
All Bloxstaking users excluded

### ISSUE THREAD

**Issue by osm4nl1** [rated-network/solo-stakers#10]
All bloxstaking users are excluded from this list. Bloxstaking is a **noncustodial** tool for setting up and monitoring validators. Blox has no control over keys nor infrastructure, users purchase and run their own nodes. 

Below are several verified blox staking nodes: 

0x88b170950cebce639e7df863e4a4660ac4c2cea3d7cae954c3a7f9a0afa22e398854ce3ef898ecfdd261a6d2ac524171

0xb615997b3bcc9b86f4be5a7ce5a7e9d4ced5971f6ce73fb4d76e67bf854be6cb427333597805dcb86ecfe7f62d750129

0xb368fa0e2dcefbdae1ed40811bb9992373357703cef6d91870d9f17bbf3838f77900496a4ad002bf7a465f908a9a9b31

**Comment by rainingjayz** [comment]
I have a number of validators through Blox, all before the merge. Really hope we can take part in the airdrop.

**Comment by Conurtrol** [comment]
I also have many validators that I set up with help from Blox. As stated previously, it is a non-custodial, non-profit service provider.

**Comment by sundeep-longledge** [comment]
Solo validator 0xb46f7d0ec58a3d25991c3167ef6720721bbfe8b33cf4d9e46c2c59ad2e190d4ad759ed417b36929949c3911e59c189e1 (ID 216540)

Began validating as a solo home staker **before** the merge, transitioned to Blox in 2023 **post-merge**.

Also as stated above Blox is a **non-custodial** service with each validator controlling their own keys and withdrawal address. Each validator uses their own dedicated AWS account. It provides a pre-configured infra running geth/prysm for validators isn't much different from AWS or GCP in this regard.

**Comment by dreamlucky** [comment]
Please include me. Solo staking with blox. 0x993db4aec7b211605aa49d1c9eb4b3d3f4b4c08a7ac216bf9c65522cf12d1e125fd6e40e1ea3c368845bbc27afedae1b

**Comment by zacksinclair** [comment]
Also had my validator nodes (Blox) excluded.

**Comment by daferna** [comment]
I don't even use Blox anymore (I run a DAppNode from home), and I likely got hit by this issue

**Comment by ariskk** [comment]
This list only includes solo stakers who [among other things](https://blog.rated.network/blog/solo-stakers) **operate their own infrastructure**.  In Bloxstaking, to the best of our understanding, Blox is operating the CL/EL clients and then their customers run the Validator Client in a separate instance. 

According to our definition, those stakers aren't "solo" as they rely on another company to provide an essential part of chain validation: the Beacon Client. 

This is an important criterion on which this list was built. This doesn't mean that's the only possible definition. In fact, this definition might not be good enough for some use cases and in those case this list shouldn't be used. There are plenty of other options out there that have different definitions with different trade offs. Projects are free to choose the one that better fits their needs.
