### ISSUE TITLE
Home Staking Validators not included

### ISSUE THREAD

**Issue by immanchand** [rated-network/solo-stakers#101]
Hello!

I've got two solo home staking validators that aren't on your list.
Index: 12972 (pre-Genesis) and 404848 (pre-Merge).

Let me know if you need any information to prove they are not a pool/cex as identified by your algorithm.

**Comment by ariskk** [comment]
Those are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5330
