### ISSUE TITLE
Home Solo Staker validators

### ISSUE THREAD

**Issue by alignment22** [rated-network/solo-stakers#102]
Please consider these validators:

Genesis Validator: 13859
Pre-Merge Validators: 169130, 169132, 169133, 169134
Post-Merge Validators: 521904, 522671, 1171260

Withdrawl Address:
0xBe1905995559A1b5273E7E331Ca1f411d9D8cCa6

Thankee

**Comment by ariskk** [comment]
Thanks for reporting.

**Comment by ariskk** [comment]
Those are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L2885
