### ISSUE TITLE
Missing solo staker validators

### ISSUE THREAD

**Issue by solostaker111** [rated-network/solo-stakers#104]
Four validators are missing (111002,111008,111132,111137)
Deposit address:
0x0E36698Fc8822A072FFf8Cdfa48F0bF74367F9EF

**Comment by ariskk** [comment]
Thanks for reporting.

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L4060
