### ISSUE TITLE
I use Abyss deposit contract to process my bulk deposit, but Rated Network recognize my validator as cex/pool

### ISSUE THREAD

**Issue by lochuan** [rated-network/solo-stakers#109]
Validator

For convenience, I used Abyss deposit contract to process my bulk deposit. As a result, Rated Network recognize my validator as a cex/pool address.

Here is my validators:

Index, Deposit Address, Withdraw Address, Status Link

1227, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/1227

185502, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/185502

185503, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/185503

402224, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402224

402225, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402225

402226, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402226

402231, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402231

402241, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402241

402242, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402242

402245, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402245

402246, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402246

402244, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402244

402228, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402228

402247, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402247

402248, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402248

402229, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402249

402227, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402227

402230, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402230

402232, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402232

402234, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402234

402236, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402236

402235, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402235

402237, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402237

402239, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402239

402240, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402240

402238, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402238

402243, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402243

402233, 0x4a3ed9A5FB04f4C433fc5DF24A4F41ddb7b3A138, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/402233

432546, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/432546

432547, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/432547

487209, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/487209

487210, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/487210

550327, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/550327

550328, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/550328

572447, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/572447

832342, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/832342

832343, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, 0x0d480e1B25006CC06F1f95eFBabE7bef62c8bCE3, https://beaconcha.in/validator/832343

**Comment by ariskk** [comment]
We are not taking Abyss into account at all. Those validators have been reported to us by a staking provider.
