### ISSUE TITLE
Pre-genesis solo staker missing

### ISSUE THREAD

**Issue by conor10** [rated-network/solo-stakers#110]
Solo staker 0xF1c9017Bfe7bb2a9f3f4951F12635C6fbc0389f0 is missing from the list. Its been running 3 validators since the genesis and is still running now.

You can see it here too https://www.rated.network/o/0xf1c9017bfe7bb2a9f3f4951f12635c6fbc0389f0?network=mainnet&timeWindow=all&idType=withdrawalAddress.

**Comment by ariskk** [comment]
Will be in the v1 :)

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L6192

**Comment by conor10** [comment]
Thank you!
