### ISSUE TITLE
pre-genesis solo staker missing (validator 1258)

### ISSUE THREAD

**Issue by DarkCenobyte** [rated-network/solo-stakers#112]
deposit & withdraw address: 0xD0eADF30EEaFA5002905C9Eb284d34bB7b523c59

validator: https://beaconcha.in/validator/0x8619b342844da0c32eaa8d3d4f130cb3c0652f6db4b01abe826a5ede12b80b0cc973f31f71b6f7d8a277c06ef16c9a11#attestations

**Comment by ariskk** [comment]
You are in the v1.

**Comment by ariskk** [comment]
Here you go https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L3720
