### ISSUE TITLE
Labeled as CEX today?

### ISSUE THREAD

**Issue by stoked5060** [rated-network/solo-stakers#115]
Everything was fine prior to today, but now when I check to claim my allocation it says I was labeled as a CEX, when I'm just a solo wallet.
0xBce3D65248341aa7238fF481e43468eD54431d70

Please fix this
![Screenshot_591](https://github.com/rated-network/solo-stakers/assets/160606615/1f4d5497-2a97-4f02-9734-1c5a31ed41c3)

**Comment by ariskk** [comment]
Hi, this doesn't seem to be a beacon chain deposit or withdrawal address. Sounds like this is a StarkEx wallet? I suspect there is some interface issue on Starknet's end. We have just provided some data wrt beacon chain deposit/withdrawal addresses, we haven't been involved in any other part of the provisions.
