### ISSUE TITLE
POS genesis solo staker 2 validators, incorrect allocation?

### ISSUE THREAD

**Issue by Proticles** [rated-network/solo-stakers#122]
I'm told that the allocation for a single pre-merge solo staker is 3600 STRK. This was my airdrop allocation, yet I have two such validators. This appears to be correctly accounted for in the published allocation list.

Could you confirm whether I still have a further allocation? I already claimed the 3600, since I assumed it was the correct amount.

These are the validator addresses:
0x94c8b5e8b54462900fc8cab39016ae4a5d2dae68a511efb480cfbec0ea3147ab8e6b692976dd3b8b3586bdd16db40433
0x95d63b69bd469b34a552401f075ba70a80b8b774d8645435ae0a0c3566ae3a5c73ad0a3c403a431a6bd244acde555bef

They share the withdrawal address:
0xc531c8B50241F48699DE93A7fC638B3251eA246b

**Comment by ariskk** [comment]
You are on the list here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L2539

Unfortunately we were not involved in the allocation process and we cannot advise on the exact amounts. Please reach out to the foundation.

**Comment by Proticles** [comment]
> You are on the list here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L2539
> 
> Unfortunately we were not involved in the allocation process and we cannot advise on the exact amounts. Please reach out to the foundation.

How do I reach out to the foundation? Btw, I can't see a way to gain access the discord. I've tried many times and despite accepting the invite, nothing further happens, the server doesn't appear.
