### ISSUE TITLE
Erroneously Classified as Blox Staking Validator

### ISSUE THREAD

**Issue by veracsz** [rated-network/solo-stakers#133]
Hello,

When I enter my withdrawal address to check AirDrop eligibility I receive the message notifying that my address is labelled by Rated Network as a node operator, staking pool provider, or a centralized exchange staker. 

After doing some research, I've concluded this is likely due to me having set up 3 of my validators through Blox Staking. The issue is however that I have not used Blox Staking services for over 5 months now. I have these three validators configured with eth-docker and run my own CL & EL via my rocketpool node. All 4 validators are on the same self-managed machine in my home. 

I'm not sure exactly how rated network determines who is a current Blox staking user, via the custom graffiti message perhaps? If this is the case, you can see that the graffiti in my most recent block proposal is a custom message and NOT blox staking. You can further see that the last blox staking graffiti message for any of my validators was over 5 months ago. 

Withdrawal address:
0xb388927d7901f2C0540e39b24960fC7926d83b9C

Deposit address:
0x0101813BECb7b9e366a55e839c12654743E57C62

Validator #1 (most recent proposal has custom graffiti):
0xa8175c28e4e48d8c37cc3789c3a8951d25c4be50a85d3d68bdfe13d095df457846ac43506b993369b49b2271dcbba574

Validator #2: 
0x903e6fa5b49ea206398063e87f785ac721b893b65b4aad2fbffe365aca9de41d748bbe936f66a2d041f56dd2573d28f1

Validator #3:
0x93d4908146028e0c85deb8c80face07dc0b4bfcc3977aa1b0cfe795191e1a8c40616fb6dc67299b51c7371246778996f (Exited ~1 month ago to participate in EigenLayer)

0x86d386b4deba0cb19b08670dd4fa0adbe4ad232fde6ed753ba8167097f28225f7855240aad551c8e0a960ffe64b23bf6 (New validator for EigenLayer)

Validator #4 (Rocketpool):
0xa8ed25d1fbd6d3c783cd6d4ae372746257e242e9cbbc9eac70c426bf884763df64cc5456c616c52010592dd631511ffd

I sincerely hope the team is able to assist me with this matter. Thank you so much for your time!

Best regards,

**Comment by ariskk** [comment]
Thanks for reaching out. To produce this dataset we used 3 months of performance data from Q1 2023. Back then, it seems like you were using Blox and thus you weren't included in the dataset. For the next version, we will use a more recent time window (likely Q1 2024) in which case you shouldn't have any issues.

Fwiw the model isn't using graffiti at all. We only look at graffiti in debugging/sanity-checking, but it isn't part of the various features as it can be easily changed to show anything the operator wants.

I will take note of the address and close this issue now. If you are not in the v2 when it is released feel free to open the issue again. Thanks!

**Comment by veracsz** [comment]
Thanks @ariskk for taking the time to review my post. I had thought the snapshot was taken Q4 2023 which is why I was confused. So if not the graffiti tags, is it safe to assume rated-network relies primarily on self-reporting from the various staking services via the API? 

If that's the case, I suppose it might be in my best interest to request that my credentials be removed from their database? 

Cheers!
