### ISSUE TITLE
Pre-merge Solo Validators incorrectly labeled as a staking pool provider 

### ISSUE THREAD

**Issue by Rickybtc2** [rated-network/solo-stakers#138]
Hi, I'm a Solo Staker that runs 7 validators but have been incorrectly labeled as a staking pool provider. Can you please fix this.

My deposit address is : 
0x0Ef7bc8a193D40a7B33074317c615C5EAe94aD20

My Validator ID's are: 
96543, 96777, 105442, 105443, 109988, 109989, 109990

Thankyou

**Comment by ariskk** [comment]
Some staking provider association detected
