### ISSUE TITLE
Automatic STRK distrubution to solo-staker addresses.

### ISSUE THREAD

**Issue by icao-eth** [rated-network/solo-stakers#141]
According to the Starknet provisions page, I have been labelled by Rated Network. Following is my address: 
0x187f7311A58baA258855fD190071411110D685F0

How will Rated Network will distribute STRK to eligible addresses? Is there going to be a claim page or will it be automatic?

**Comment by ariskk** [comment]
This address doesn't seem to be a staking address. There was a bug in the provisions website where it pointed people to Rated regardless to whether the address was a staking address or not. We only provided staking related data to StarkNet and we weren't actually involved in the allocations. I would recommend to reach out to StarkNet.
