### ISSUE TITLE
Another solo validator missing from list

### ISSUE THREAD

**Issue by edrews** [rated-network/solo-stakers#16]
I've been a solo staker/validator staking at home in my basement since the launch of the beacon chain, using Prysm for consensus and Erigon for execution.

Deposit and withdraw address is 0xE2EFFFfE7fB7015862cBb1958A30967e48030cFF

I currently run 13 validators with the following indices: 1256,401557,405852,405853,405855,405856,405857,405858,405859,405860,405865,405866,405867

Please consider adding my address as a solo validator to your list. Thank you!

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L6113
