### ISSUE TITLE
Solo and Rocketpool validator missing from list

### ISSUE THREAD

**Issue by Akuma0408** [rated-network/solo-stakers#17]
I have been a solo staker since early 2020 and wasn't in the list.

Deposit and withdrawal address is 0x7CA545eBc6153765330F37749E1c1A362F63f05e

I had three validators less than 500k, and one Rocket pool validator below: 138198 - exited feb 2024, 138203 and 138204. The two latter are still active. 

I run four Rocketpool validators: 482098, 757034, 818876 and 1023886.

I think it is quite strange my address with 400 defi TXs, POAPs etc. is excluded but a fresh wallet with only a deposit to the beaconchain is 100% a solo validator like this one: https://etherscan.io/address/0x658d1df2e10c43ac70b5b88bd1f9a498c78c1d76

Please consider adding my address as a solo validator to your V2 list. Thank you!

**Comment by Akuma0408** [comment]
Above was a duplicate post I mistakenly created.

**Comment by ariskk** [comment]
Here you go https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L2562
