### ISSUE TITLE
Solo validator missing from the list

### ISSUE THREAD

**Issue by cexedev** [rated-network/solo-stakers#18]
I am a solo staker, but not included in the list, My withdrawal address is `0xA16024Ef452710675aFF747c6A4AaC50D23e01Cb` 
I have 2 separate deposit addresses that I can provide if needed.

**Comment by ariskk** [comment]
I can see the withdrawal address on the list https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v0.csv#L2474
