### ISSUE TITLE
EigenLayer native restaking - EigenPods should not be the eligible address

### ISSUE THREAD

**Issue by DigiDr** [rated-network/solo-stakers#19]
Genesis stakers eligible for $STRK (and future) airdrops may have set their 0x01 credentials to EigenPods (EigenLayer management contracts) for native restaking. They won't be able to sign messages proving ownership of these contract addresses. This is similar if not identical to the Rocketpool issue and I would suggest that in future and instead, their eligible address should be equal to the deployer of that EigenPod.

**Comment by ariskk** [comment]
Hi! Unfortunately we have no control over those processes, we merely provide a list of deposit addresses. How downstream consumers use this list to power applications is completely up to them.
