### ISSUE TITLE
Solo Staker before the Merge Classified as Staking Pool

### ISSUE THREAD

**Issue by savagefit** [rated-network/solo-stakers#20]
Hello, as you can see from my validator below I have a solo staking eth node that was launched under blox which is just a GUI tool. However I’m mistakenly being approved under a staking pool or cex pool. I need to be added to the single staker list.  You can clearly see my deposit address of 0x16D088a79D7d36213618263184783fB4d6375e33 on the beacon scan below and confirm on the provisions site it doesn’t display correctly for the airdrop. 

https://beaconcha.in/validator/0xb615997b3bcc9b86f4be5a7ce5a7e9d4ced5971f6ce73fb4d76e67bf854be6cb427333597805dcb86ecfe7f62d750129#attestations

**Comment by ariskk** [comment]
Blox is a special case that has been excluded. Our understanding is that Blox operates the Beacon Client and EL Client, and Blox stakers just run the validator client in a separate preconfigured AWS account. We have only included stakers who run the whole full infra set themselves in this list.
