### ISSUE TITLE
Rocket Pool Validators Pre-Merge Missing

### ISSUE THREAD

**Issue by esheng94** [rated-network/solo-stakers#21]
Hi! Thank you for open-sourcing your list of solo-stakers. This is really helpful information for the community. 

Please note you may have excluded some Rocket Pool validators that were pre-merge / pre-500000 index

For example: 
1. https://beaconcha.in/validator/352919 - deposit address 0x51980eC616652B7B17C36f25bfe039BA0F97F5c1
2. https://beaconcha.in/validator/456514 - deposit address 0x51980eC616652B7B17C36f25bfe039BA0F97F5c1

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L3911
