### ISSUE TITLE
Solo staker - not in list/misclassified as pool

### ISSUE THREAD

**Issue by Genesissolostaker** [rated-network/solo-stakers#24]
Hi,

I have a total of 14 validators, 10 pre Genesis and 4 post, my indexes are literally double digit - I was basically one of the first persons to deposit. Yet I can't find myself in the list.

Withdraw address: 0x42751916BD8e4ef1966ca033D4EA1FA2a8563f88
Deposit address: 0xA56169dBB826A7146572389D3696600fa5dca575
Validator indexes: 40,41,42,43,44,45,46,47,48,52 

I have 4 other validators running after genesis, they all have the same withdrawal address set, the 4xxxxx indexes have a different deposit address, but same withdrawal. Indexes: 441317, 441318, 441319 and 574767.

**Comment by ariskk** [comment]
Here you go https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L6541
