### ISSUE TITLE
Solo staker missing from list

### ISSUE THREAD

**Issue by zellster07** [rated-network/solo-stakers#27]
Here are two longstanding solo stakers missing:

Validator: https://beaconcha.in/validator/26894#deposits
Wallet: 0x9ad4D3ae94Ba9156B0dBc1E036047C7a435D087C

and

Validator: https://beaconcha.in/validator/273219#deposits
Wallet: 0x9897B34B6C11d2a55af9cE886Fb927b39c69392F

**Comment by ariskk** [comment]
You are here:
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L2483
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L4741
