### ISSUE TITLE
Solo staking validators not included in your list 

### ISSUE THREAD

**Issue by ethSoloStaker** [rated-network/solo-stakers#31]
11 x solo staking validators missing off your list
deposit address 0xE26E1d239d27e1FE8c7a150c5c266b347A7A6E7c

5 x genesis 
5 x pre-merge
1 x post withdrawals

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5322

**Comment by ethSoloStaker** [comment]
Thank you for you hard work to update the list.
