### ISSUE TITLE
Genesis solo staker

### ISSUE THREAD

**Issue by kernelwhisperer** [rated-network/solo-stakers#34]
I'm a solo staker too, staked from my home.

https://beaconcha.in/validator/98cbee30ee7c0c26fb05f03384af24118c50b14095c3faefcfb4935d959bf834b16b2b7810fb9c2f4b7acfd7e0d04a16#attestations

https://etherscan.io/address/0xfa42dC95E344f976d4B043Ca227c474470B670DC#beaconchain

**Comment by ariskk** [comment]
Hm, because this validator wasn't active throughout the whole period we used to conduct the analysis (~Q1 2023), we didn't have enough data to use and thus it is unclassified. I am not sure how those cases are treated in terms of the airdrop tbh. Not a lot we can do at this stage unfortunately.

**Comment by kernelwhisperer** [comment]
@ariskk where can I see the criteria for the original research?

My validator was active from genesis up until March 6, 2023.

**Comment by kernelwhisperer** [comment]
Is there any harm in including my address in the list, _manually_, especially given the period you conducted the analysis is not concrete?

**Comment by kernelwhisperer** [comment]
@ariskk can we reopen this? Thank you!

**Comment by ariskk** [comment]
@kernelwhisperer we aren't adding addresses to the list manually as this can create a slippery slope. The period of time used to conduct this research was Q1 2023 (so say 1/1/2023-31/3/2023) and there was a requirement that only validators active throughout the period were included. I suspect by exiting on the 6/3/2023, you were excluded from that set.
