### ISSUE TITLE
Solo staker -pre merge,  misclassified as pool

### ISSUE THREAD

**Issue by SplinterCole** [rated-network/solo-stakers#36]
0x5f055f332C4A5bA920D934Ff69CD1Bf747eCe5b9  (same deposit + withdrawl adress)

https://beaconcha.in/tx/0xf9991183d78d444e96d7c389b7d9f3c2f53d9359c9420eadb273fa7ad9e5b523

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L6285
