### ISSUE TITLE
Missing solo staker index 20163

### ISSUE THREAD

**Issue by ethereumpools** [rated-network/solo-stakers#37]
It can be verified on-chain that validator index [20163](https://beaconcha.in/validator/20163) deposited from [this address](https://etherscan.io/address/0x6d32f67765bb0e426c7b64de30a61998ea9d4638) and staking since genesis, is indeed a solo staker and missing from the list.

Related: https://github.com/rated-network/solo-stakers/pull/12

**Comment by ariskk** [comment]
I can verify this is indeed a solo staker, and will be included in the v2 of the list.
