### ISSUE TITLE
Genesis solo staker missing

### ISSUE THREAD

**Issue by inplayrs** [rated-network/solo-stakers#39]
I'm a home solo staker from genesis and misclassified as pool.

Deposit address:  0xA3Fe70056D2d58E051fC981AaDA3b7d23dDba49D
Validator: https://beaconcha.in/validator/941a9a9a35ca8294ee389b3d4770398ecb41ead78b5389abd03e560e28e351deb6379819c1bc59329db3ff9715776127#attestations

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5779
