### ISSUE TITLE
Dappnode solo validators are missing on the list

### ISSUE THREAD

**Issue by GitShyMoon** [rated-network/solo-stakers#4]
Solo validators using Dappnode are missing on the list although they proposed a block with the Graffiti **validating_from_DAppNode**.

If some got thrown out despite the Graffiti, this could be adjusted in further versions. I have a friend of a friend ;) which is a clear solo staker with Dappnode [index<500k; 1 validator] but not on the list.

**Comment by BologneseSauce** [comment]
Yes, i am a Dappnode solo staker and my wallets are not on the list.

**Comment by Weifarer** [comment]
Hopefully this information provides some help in optimizing the methodology as my node is not on the list:

1. I’m a single node validator in the 400ks using Dappnode. I didn’t have a block proposal before the “snapshot” was taken, so I guess my dappnode graffiti wouldn’t have helped anyway.

2. I made the Beaconchain deposit on one wallet and set the withdrawal address to another wallet. Both wallets haven’t had any interactions with other nodes afaik.

**Comment by ariskk** [comment]
The list has been updated to contain an expanded set. Please check again. If you are still not there, please open an issue with additional information (addresses, indices, pubkeys) and we will investigate.
