### ISSUE TITLE
Validator 24706 missing from list

### ISSUE THREAD

**Issue by magnetarc** [rated-network/solo-stakers#41]
I have one validator (24706) that was set up a few days post-genesis. The Rated list that was widely distributed does not contain this single, solo validator. I think this list should be updated or retracted since, from the feedback you can see, there are a vast number of errors affecting genuine node operators.

Validator: 24706
Deposit Address: 0xC83323E21c754ddeC728e6Cf08d5BCE14AFbf41C (istake.eth)
Withdrawal Address: 0x47476Eee389Ab9bc767E9603812175C9DaB5737E

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L3504
