### ISSUE TITLE
Pre-merge solo staker wrongly categorized as a node operator

### ISSUE THREAD

**Issue by dongwon0308** [rated-network/solo-stakers#42]
Solo staker with 15 validators wrongly categorized as a node operator/cex.

0x42f5cbf04b61c890d338f8ffe2fa36138a7ab413

**Comment by ariskk** [comment]
According to our records this validator is run by Allnodes and thus correlated with the 25.6K validators Allnodes are running.
We will look into listing those in a separate list.
