### ISSUE TITLE
Solo genesis validator and two solo pre-merge validators wrongly categorized as a node operator/cex.

### ISSUE THREAD

**Issue by Berlin-Miner** [rated-network/solo-stakers#44]
Hi,
my fist validator is running since before genesis, the deposit is made on 24-11-2020, the deposit address is:
0x0b934b1118ee6E9Cd9D5a6F22eF561BaefD04a92 - it is not part of your list
A month later I made two more validators, the deposit is made on 29-12-2020, the deposit address is:
0x35BF8C46267B481E7ffB5dE7b81e4dCe8b0AFB99 - it is not part of your list
The withdrawal address for all three validators is:
0x9BDD3915882Cc98fd9973c5eF71A3312965Ae205 - it is not part of your list
The third validator is exited shortly after withdrawals were enabled.

**Comment by ariskk** [comment]
According to our records those validators are run by Allnodes.
We will look into listing those in a separate list.

**Comment by Berlin-Miner** [comment]
They were not run by Allnodes, from when they were first turned on till after the Merge. My housing arrangements changed at some point in time and I moved to Allnodes. I am not sure how to move them from Allnotes to my house, but I am thinking about it.

A question: Am I not a Solo validator if my nodes are running on the cloud or Allnodes? All the ETH is still mine.
