### ISSUE TITLE
Solo staker missing from list

### ISSUE THREAD

**Issue by dec3ntraliz3d** [rated-network/solo-stakers#47]
Please add below solo home staker to the list. 

https://beaconcha.in/validator/376536
deposit address: 0x99cbA4f7320e62Adf396091Be65028E5CC195DE7
withdrawal address: 0x8a60a233F03B2E78889031efA9B4c4aDA6aA4c7d

**Comment by dec3ntraliz3d** [comment]
Is there anything else you need from me, let me know. Thanks

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5903
