### ISSUE TITLE
December 2020 home solo staker missing/misidentified from list

### ISSUE THREAD

**Issue by TheHansGruber** [rated-network/solo-stakers#48]
December 2020 deposit address 0x942957Bff64620cED7029408c5e73b2fb5527AaF

Validator index #35689

Withdrawn October 2023 for opsec purposes to withdrawal address 0x9768339588DD531096222A99c4d258d646b76a80

Withdrawn eth sent to new home solo validator deposited October 2023. Funds can be traced to original withdrawal address. Deposit & withdrawal address' are the same. 0x136C8b89eDB8151a6C9011fCD53Fc51Cc667a5eA. Unrelated to this issue, but should be included in the rated solo stakers list moving forward.

Possible reasons for misidentification:  dust test transactions to/from coinbase for opsec & validator index #35689 had the same withdrawal address that I had set for my rocketpool minipools.

Original withdrawal address shows provision of 360 STRK instead of 1800.

**Comment by ariskk** [comment]
Here you go https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L4275
