### ISSUE TITLE
Stader persissionless operators are not in the list 

### ISSUE THREAD

**Issue by jncharon** [rated-network/solo-stakers#5]
It looks like the list doesn't contain Stader's Permissionless NOS like this one : 
https://beaconcha.in/validator/90a6c9a9eb29393e6d20c16a00d45ac1a1505290c996a225e57134474e79b594f6645d7fc82d45689d74b2fc0de7cfac
You can identify them because they have 2 initial deposits : one from 1ETH and 31ETH from the protocol

**Comment by ariskk** [comment]
The `v0` list only covers validators activated before the `27/11/2022` (which is before Stader launched iirc). So it's only up to validator index ~500K.

We are working on a new version that covers additional indices.

**Comment by ariskk** [comment]
Closing this. Stader Permissionless validators will be considered in a future version of the list. Stader launched way after the validator indices this list covers.
