### ISSUE TITLE
Genesis solo home staker missing from list

### ISSUE THREAD

**Issue by tinysnowman** [rated-network/solo-stakers#51]
This validator is a solo home staker that has been running since genesis:
https://beaconcha.in/validator/15268

Deposit address:
0xe76336a7a6C9F7816497785d77d5308A65B5A0C2

The deposit address does appear in this list:
https://github.com/GLCNI/ETH-Solo-Validator-Addresses/blob/main/Solo-Stakers/Solo-Stakers-A.csv

I hope you can refine your code to get closer to the true list!

Thanks for your efforts on this.

**Comment by ariskk** [comment]
Here you go https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5567
