### ISSUE TITLE
Solo staker missing

### ISSUE THREAD

**Issue by Cinstaker** [rated-network/solo-stakers#52]
Please add below solo home staker to the list.

Validator indices: 25031, 25032, 25033, 25034, 25035
deposit address: 0xd8F2028fbA1dA24558eA4Ae50Ca774573a9090cD
withdrawal address: 0x40d02eAFc7f241cb870E0f07aeB12E23b817fCe5

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L1664
