### ISSUE TITLE
Solo staker incorrect allocation

### ISSUE THREAD

**Issue by swazipi** [rated-network/solo-stakers#53]
I am a solo staker and run four validators. These validators have been running continuously since shortly after genesis and well before the merge. The provision checker says the deposit address is eligible for 1800 STRK but I believe it should be 7200 (1800/validator * 4 validators running since genesis but before merge). Provision checker says the withdraw address for my four validators is not eligible to receive any STRK. Are you able to correct the allocation?

Deposit: 0xB122a735828a47a2181F1F7ED6ADC357bb3Ff53b
Withdraw: 0x2CAf9E690b9B33FD1EC6DfcA52AD4eB628ee401b
Beaconcha.in link: https://beaconcha.in/dashboard?validators=68473,159730,159883,172761
Transactions, one for each deposit from f53b address above:
1)
https://etherscan.io/tx/0xe380c4c525c49ec4caf9c057ea70f4b2b330eca462a8a2f6f9ae0032d3b6bff6
2)
https://etherscan.io/tx/0x368e46002faf10a3d84f3516eafcb8f222c951a557ab1ccc3e951093a96a8dd7
3)
https://etherscan.io/tx/0x72e15635bc24cf437cae6c86081b595c34533d2587ad25377817c0fca249ba70
4)
https://etherscan.io/tx/0xb5d9f9e81dc369f00235f7132ba39ac96333af83d0a7a7cba2fd0191852c471b

I staggered my deposits. At first I deposited enough to run one validator, then I added two more, then I added a final one. I have been running these validators continuously from before the merge till now. Maybe the staggering was the issue?

Thank you for your time and consideration.

**Comment by ariskk** [comment]
Your deposit address is on the list and has a high score
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v0.csv#L4338

Unfortunately we have had no involvement in the actual distribution mechanism; we merely provided the list. Please reach out to Starkware.

**Comment by swazipi** [comment]
I'm sorry I don't understand what you mean by high score, can you explain? I was allocated 1800 tokens only when I should have received 7200.

Yes my address is on the list but I think because I did not change withdraw credentials from 0x00 that your list only counted one validator of four for some reason, which is why I was allocated 1800 instead of 7200.

thanks for any additional insight @ariskk
