### ISSUE TITLE
Solo Staker Incorrectly Not Included on Solo Staker List

### ISSUE THREAD

**Issue by TSconnector** [rated-network/solo-stakers#55]
20 validators total, deposited from 3 different addresses:

0x97EFC8ede7Fa5cA7d914d30b50986a4266fD1e1D - Nov. 22, 2020 (5 validators) (pre-beacon chain launch)

0xFD7557E38Bc65Ee8Bf35c412B8D50487e827Fd8d - Sept. 9, 2022 (10 validators) (pre-merge)

0x28987304F31466B108F970a2e74Cf3676b3Af4B8 - May 22, 2022 (5 validators)

None of these deposit addresses are included on your list. Withdrawal address for all is: 0xC895A0F3D3D0D4F226934D756252e07Af90fD45d

**Comment by ariskk** [comment]
The firs two
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L4872
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L4596

The third one has validators with indices over 700K and thus it is out of scope for the v1.
