### ISSUE TITLE
Genesis Solo Staker missing

### ISSUE THREAD

**Issue by janek26** [rated-network/solo-stakers#58]
my solo validator is not on the list! :) It's a dappnode from home, index 7741

Thanks for all the hard work guys! For any questions reach out on twitter, happy to help

**Comment by ariskk** [comment]
Thanks for reporting! We will look into it.

**Comment by ariskk** [comment]
It's here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L4762
