### ISSUE TITLE
pre merge validators wrongly labelled as pools

### ISSUE THREAD

**Issue by strobo24** [rated-network/solo-stakers#59]
withdrawal address for 2 pre merge validators seems to be wrongly labelled as pools: 0x2c537ac6209b5E392207783DF4671fdb932aFf44

deposit address for the validators was: 0xA87d73c1e8F5b814552AD446824092645fB839B1

**Comment by ariskk** [comment]
Thank you for reporting. We will look into it.

**Comment by strobo24** [comment]
thanks @ariskk ! The withdrawal address I mentioned above was also used after the merge to create a rocketpool minipool. I wonder if the algorithm recognizes that two  pre-merge validators are associated with the withdrawal address, but because it is later used for creating a mini pool, it wrongly thinks the two pre-merge validators were also pools

**Comment by ariskk** [comment]
That shouldn't be a problem. We haven't actually tagged Rocketpool validators as neither pool/cex/pros nor solos. Because Rocketpool is a mixbag of solos and professionals, we let the algorithm distinguish between those. Will review all the issues again once the updated version is released.
