### ISSUE TITLE
Solo + Rocketpool Validators missing

### ISSUE THREAD

**Issue by cschneider1984** [rated-network/solo-stakers#6]
Dear Rated.network,

first of all, awesome initiative!

I wanted to report that both, my solo-validators as well as Rocketpool validators are missing:

Solo validators (deposit address: highflyer.eth = 0x5F561EB8B4380886BD3Bbdc87FB4c28C0353B71a):
- 166915
- 179393

Rocketpool validators (deposit address: rocketpool.highflyer.eth = 0x22157C72aB16A98897B923F9A5819449a7e2e877):
- 260570 
- 307518
- 594005 (FYI, as the list only covers validators below index 500000)
- 594019 (FYI, as the list only covers validators below index 500000)
- 594063 (FYI, as the list only covers validators below index 500000)
https://rocketscan.io/node/0x22157C72aB16A98897B923F9A5819449a7e2e877

The solo validators' withdrawal address points to a Safe wallet (safe.highflyer.eth = 0x372d29C978f9Fb10c28563557dbb65b61a08aE49). The Rocketpool validators' withdrawal address follows the Rocketpool logic.

Happy to provide additional information, if needed and would be very interested to know what disqualified my addresses.

I'm running my node at home (Germany) on an Intel NUC.

**Comment by cschneider1984** [comment]
Wanted to raise this again in light of the StarkNet airdrop today:

My withdrawal address (0x372d29C978f9Fb10c28563557dbb65b61a08aE49) has only been allocated with 720 STRK, which would mean that both of my solo pre-merge validators have been incorretly classified as being in a staking pool. They were both funded by my main ETH address highflyer.eth = 0x5F561EB8B4380886BD3Bbdc87FB4c28C0353B71a, which clearly does not belong to any pools.

Pre-merge Rocketpool validators as mentioned above (indexes 260570 and 307518) were correctly assigned 1800 STRK each.

I kindly ask you to correct your dataset.

**Comment by ariskk** [comment]
You are here
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L3853
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L7604
