### ISSUE TITLE
Pre-genesis solo validators misidentified as a pool

### ISSUE THREAD

**Issue by solo-staker** [rated-network/solo-stakers#60]
Indices 20076, 20077. My Starknet allocation was 10 % of the pre-genesis home staker allocation, so that must mean I am identified as pool.

Indices: `20076`, `20077`
Deposit: `0x27F60BdDBB55e88f1c05C73F074f158acfAacc0B`
Withdrawal: `0xBE8859cA9C3B0AA3B55644B9fD90017512A80801`

**Comment by ariskk** [comment]
Thank you for reporting. We will look into it.

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L4900
