### ISSUE TITLE
0x00 Stakers Only Counted For One Validator

### ISSUE THREAD

**Issue by Christina0007** [rated-network/solo-stakers#61]
For the Stark airdrop 0x00 validators with multiple validators have only received credit for one validator instead of the respective 3600/1800 * x validators on their deposit address.

I'm raising this issue on behalf of myself and several other posts I've seen on EthFinance and the EthStaker community that all have the same issue. Everyone I've spoke to that has this issue has 0x00 validators (so no withdrawal address) and multiple pre-merge or pre-beacon validators but is only receiving credit for one.

Cheers and thank you for your time!

**Comment by ariskk** [comment]
Thanks for reporting. Unfortunately you need to bring this up with Starknet. We were not involved in how the tokens were allocated, we just provided some data.
