### ISSUE TITLE
Pre-Genesis Solo Staker Not Included

### ISSUE THREAD

**Issue by ganondorf8** [rated-network/solo-stakers#63]
Hi,

Validator with index 249237 is not included in the list. I guess my validator is mistaken as a pool member (also by beaconcha.in), which is not true. I am a solo staker with 1 validator running lighthouse/geth at home.
Here some infos:
Deposit address: 0x3397CB6853DFA172B160637B843ADc2d59E6B59b
Validator index: 249237
https://beaconcha.in/validator/8982faf2a6a7c4fe6d9e78383574eee0a3637ae57562eee9e32ec15247af48c478b8315ddf3c10068cf2dc55242fcfe9#deposits

As you can see i modified the name of the validator on beaconcha.in, which is only possible if being in possession of the private key belonging to the deposit address.

BTW: I have not set any withdrawal address yet.

**Comment by ariskk** [comment]
Thank you for reporting. We will look into it.

**Comment by ganondorf8** [comment]
Thank you! :)

BTW: i now set my withdrawal address.

Full validator info:
Validator index: 249237
Deposit address: 0x3397CB6853DFA172B160637B843ADc2d59E6B59b
Withdrawal address: 0x9E12Ab4646D97bc33d156D795Ab64C50984eF7cb
https://beaconcha.in/validator/8982faf2a6a7c4fe6d9e78383574eee0a3637ae57562eee9e32ec15247af48c478b8315ddf3c10068cf2dc55242fcfe9#deposits

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L7822
