### ISSUE TITLE
This data set is a joke

### ISSUE THREAD

**Issue by EvilJordan** [rated-network/solo-stakers#65]
Look at the missing stakers in the open issues.

Doxxing oneself is also not ideal.

Perhaps this isn't the way to go and you should figure out something better.

Additionally, the instructions to DM on Twitter or in Discord: The WenMerge Twitter doesn't allow DMs from unverified accounts (I am not paying for that shit), and there is no link to a Discord anywhere. You guys need to get your shit together or call this off.

**Comment by ariskk** [comment]
We (Rated) have never provided any instructions to message anyone on WenMerge Twitter or Discord. I am not sure where this came from, please stay safe.

**Comment by EvilJordan** [comment]
https://x.com/Wenmerge2022/status/1758057366128640136?s=20

YOU didn't, but this is happening right now.

Also, way to dodge the part where the data set is completely flawed.
