### ISSUE TITLE
solo/genesis validators missing but don't want to doxx myself

### ISSUE THREAD

**Issue by pyggie** [rated-network/solo-stakers#66]
I run several validator instances -- Dappnode at home, RocketPool on Dappnode, EigenPod on Dappnode, and two more in the cloud, including one genesis validator -- and most of them are missing from this dataset.

I don't want to doxx myself and link these to my public github persona by posting them here.

I'm sure many hundreds of other solo stakers are in the same situation.

Please just step back and completely restart your solo staking effort. I suggest you take a look at this repo for a better approach:
https://github.com/GLCNI/ETH-Solo-Validator-Addresses

**Comment by ariskk** [comment]
You could create a burner GitHub account and report an address.

**Comment by EvilJordan** [comment]
You could have gotten your data set right and not caused chaos?
