### ISSUE TITLE
missing solo stakers

### ISSUE THREAD

**Issue by ethstakerr** [rated-network/solo-stakers#67]
I run a solo staking validator for the following addresses missing from current list:

* Deposit addr 0x2E2f4DFA542d6d8b4817Ce45614016f452647439
* Withdrawal addr 0x8B021A0D0e113746c79f0eF8c396aDE292Ec9030
* Genesis - 1 validator (# 12654)
* Pre-merge - 29 validators (# 30476 ... 244081)
* Post-merge, Pre-Shapella - 70 validators (# 432631 ... 440949)

**Comment by ariskk** [comment]
This address can be found here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L7434
