### ISSUE TITLE
Wenmerge Representing Solo Validators

### ISSUE THREAD

**Issue by WenmergeDev** [rated-network/solo-stakers#68]
Hello,

We are representing several solo validators who have reached out to us to be added in the list of solo stakers:

Validator IDs: `301593`, `413003`, `422459` - [solo staker mislabeled]
Validators running on the address `0x774F45a32cA6A365B693Dfd58d129c959fC159D9` - [Only received 4000 STRK, it should have been 50,400 STRK]
Validator ID: `249237`
Validator ID: `7508` - [Solo validator at genesis 
Validator ID: `579367` - [Added April 2023] 
Validator ID: `579374` - [Added April 2023]
Validators running on the address `0xd083262f13b9713d8a32ef9d11360e2ce1bea58c`
Validators with deposit address `0x3886A5b7972d6FeDE8Ae87a1bC933a78A645A023`, withdrawal address `0x42a63047a1cD8449e3E70aDEB7363C4Ca01DB528` and `0x751fa5Fc8B96454B0CCA47d640E1d79e42624c14`

Thanks

**Comment by ariskk** [comment]
Thanks for reporting. We will look into this.

**Comment by ariskk** [comment]
Most (if not all) of them are in now, eg
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L6573
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L3252
