### ISSUE TITLE
Dappnode solo staker

### ISSUE THREAD

**Issue by baraba80** [rated-network/solo-stakers#69]
Hello, I am solo staking via dappnode and I did not get any airdrop
10 validators running 893755, 899906, 933229, 933230, 933231, 1000879, 1024960, 1024961, 1089398, 1116797. 
deposit address 0x4066dDc98D75428eBC5C232328Ae564d4F10F535
I know that validators are wit high index, but I am contributing :)
Thank you!

**Comment by ariskk** [comment]
Thanks for reporting! The current list only covers deposit addresses for validators who were activated before the merge (so up to index ~450K). 

We will soon produce a v2 covering all the way to index ~900K, so we will take this into account then.
