### ISSUE TITLE
Quite a lot of Solo Validators missing from list, and some POAPs not working to give confidence it's solo

### ISSUE THREAD

**Issue by danw-eth** [rated-network/solo-stakers#7]
Most of mine and my friends Validators missing from the list, not sure if the confidence levels are that accurate? Small sample set but the only ones I've checked are all missing.

Mine should be pretty obvious, running on non-popular IP address locations in Australia where there are no datacentres. Setup is just an Intel NUC at home with Ubuntu. Running minority clients as well which could add some confidence.

Also I noted that POAPs are a method used, this address does have 3 Ethstaker POAPS: https://collectors.poap.xyz/scan/0xc49e4d304c35c780373A6F80551EfFf7CAb403f0

Note that some other POAPs I receive I transfer to another address so it could also be useful to look at POAP sends as well, though my address still has 3 of the staking related POAPs.

Deposit address 0xc49e4d304c35c780373A6F80551EfFf7CAb403f0, first index starts at 79310

I also have rocketpool validators but they didn't start until index 726826. Something to check for v2.

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L6598
