### ISSUE TITLE
Solo Staker Since 12/20 Not Properly Allocated

### ISSUE THREAD

**Issue by MeowMeNot** [rated-network/solo-stakers#70]
I have been running three solo validators since 12/20. Their indexes are in the 37,000 range. I was only allocated 360 per validator for a total of 1800 STRK.

I never set a withdrawal address (0x00 validator), but my deposit address is: 0xa43C3FA89a6ff585f324D848C198E3641dF6e873

Please let me know if any further info is needed.

Thanks in advance.

**Comment by ariskk** [comment]
Thanks for reporting. You are actually on the list https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v0.csv#L4338

We don't control how the list is used downstream unfortunately. We will pass that information forward to the relevant third parties (Starknet in this case) and then it's up to them.
