### ISSUE TITLE
Solo staker mistaken as a pool or cex

### ISSUE THREAD

**Issue by magicmurph** [rated-network/solo-stakers#71]
I get this message

The Starknet Foundation
is in touch with your organization.

If you are here, it means you have been labelled by Rated Network as a node operator, staking pool provider, or a centralized exchange staker. As such, you are eligible to receive more than one million STRK, to be distributed further to your individual stakers. The Starknet Foundation will be in touch with someone from your organization.

My node address is 

0xbd0E8Fc3d1A704BC66e759903040F07Bae161dd3

Thanks

**Comment by ariskk** [comment]
The validators in this address have been reported to us by a non-custodial staking provider. Please reach out to them to find out how the process will work.

**Comment by magicmurph** [comment]
I did they said just go to the claim site. On Feb 17, 2024 1:24 AM, Aris ***@***.***> wrote:
The validators in this address have been reported to us by a non-custodial staking provider. Please reach out to them to find out how the process will work.
