### ISSUE TITLE
Yet another Genesis Solo Staker missing

### ISSUE THREAD

**Issue by simbesh** [rated-network/solo-stakers#72]
Same here

12 validators (2 pre-genesis 10 post-genesis):

Genesis validator indices: 9695, 9696
Pre-merge validator indices: 35490,35491,35492,35493,35494,35495,35496,35497,35498,51316

10 validators Withdrawal address: 0x8d43bc364F8bD4aFD491cB27FDC738C44F9CC393
9696 withdrawal address: 0x8Ae16d842A853365E6a1EE7eD2A0c80b8fE298aC
51316 withdrawal address: 0x2f4c3929C68739AF7a4d87aB309d871e7D58A2d8

Home staker not using any service or allnodes

**Comment by ariskk** [comment]
Thanks for reporting. We will look into it.

**Comment by ariskk** [comment]
You are here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L6321
