### ISSUE TITLE
Solo staker mistaken as pool/cex validators

### ISSUE THREAD

**Issue by NicolasMassart** [rated-network/solo-stakers#73]
Hi,
I have 4 solo validators that all have the same withdrawal address for convenience.

They are flagged as cex/pool as they are not in the solo list here when I actually have all the control on each of them.
Thanks to add to the list.

See associated withdrawal address: 0x38c02f9b1fa8c729574e28e1d2e98a7b76d69f82

**Comment by ariskk** [comment]
Thanks for reporting. We will look into it.

**Comment by NicolasMassart** [comment]
Will this be taken into account for Starknet drop today?
Thank you very much!
🤞🤞🤞

**Comment by ariskk** [comment]
Here you go https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5381
