### ISSUE TITLE
Solo Validator 378505 (pre merge) mistaken as CEx

### ISSUE THREAD

**Issue by reapz69** [rated-network/solo-stakers#74]
hi I run 1 node 

Validator 378505
deposit address 0x2BcfB6355c57646cd196CE4F14a8caf571a10e58
withdrawal address 0x9F8a1EA3C131B8F837E03FE8f8722A02e688c88C

**Comment by ariskk** [comment]
This validator has been reported to us by a non-custodial staking provider. Those validators have been excluded from our definition of "solo", but this doesn't prevent downstream consumers from rewarding them.

**Comment by reapz69** [comment]
If I transer it to aws will you add it to the list?
