### ISSUE TITLE
Solo staker identified as CEX/Pool/..

### ISSUE THREAD

**Issue by askesisdev** [rated-network/solo-stakers#75]
Deposit Address | 0xd7992BA950b89A4225d487A1c5878a50C11A3c08 |  
Withdrawal Address (0x01) | 0x0D319058F592158483062D48152bd84e9a2e7CFE

Validators: 92046 92047 92048

I'm a solo staker and it was identified as CEX/etc as AllNodes. They are only providing technical services but the validators are mine. I'm a solo staker, just using a VPS/technical provider instead of running it from home due to Internet/travel issues.

**Comment by ariskk** [comment]
Thanks for reaching out.

According to our definition of "solo staker" as described in the original [research](https://blog.rated.network/blog/solo-stakers#validator-selection), non-custodial staking services are excluded. We have provided a list of those though, so it is up to the downstream consumer to decide how to use that data (ie they may choose to treat those cases as "solo" or "not solo", that's outside of our control).

**Comment by askesisdev** [comment]
I'm moving to be a home staker anyway as I'm not willing to risk more airdrops. There is any way to update my validators to solo stakers as soon as I have migrated from AllNodes?

Thanks
