### ISSUE TITLE
solo staker

### ISSUE THREAD

**Issue by newwanger** [rated-network/solo-stakers#77]
hi, I am a solo staker via dappnode since 2020-12-05 and I get 0 with the airdrop.
index 33678 33679 33680 33681 33682
deposit address 0xC0567a6fe0f3083603D639c8233024E8bD1926d6
withdraw address 0xC0567a6fe0f3083603D639c8233024E8bD1926d6
thx.

**Comment by ariskk** [comment]
Those validators seem to be operated by a staking provider (they have been reported to us by them).

**Comment by newwanger** [comment]
no ser ,I'am a solo staker
![微信图片_20240217181847](https://github.com/rated-network/solo-stakers/assets/95598188/d1638048-1f48-442f-9f2f-14866d611948)

**Comment by newwanger** [comment]
@ariskk
