### ISSUE TITLE
My allnodes validators were not included

### ISSUE THREAD

**Issue by 0xCSMNT** [rated-network/solo-stakers#78]
My deposit address is: 0xEE48671f1E55BEF74103b5C496E861c18Ee71dad

Validators: 73734 73735 73736 259908 276806

Do I need to get rewards from allnodes, or can you just send them to my deposit address directly?

**Comment by ariskk** [comment]
My understanding is that Allnodes will handle this. That said, we haven't been involved in the actual distribution so it is unclear to us how the process will work in practice. I would suggest to reach out to Starknet to clarify.
