### ISSUE TITLE
Allnodes solo staking addresses are not on your intial list

### ISSUE THREAD

**Issue by jdgsb** [rated-network/solo-stakers#8]
Many of us are huge fans of solo staking but don't have stable enough internet connections in our locations. Please work with Allnodes to make sure our individual solo staking addresses are included in your lists. Thank you.

**Comment by jagmot** [comment]
Allnode addresses are eligible. I just checked. 

Make sure to select Ethereum and use your withdrawal address. Also make sure that your validators were live prior to the merge. 
![Uploading starket.jpg…]()

**Comment by naman14** [comment]
@jagmot do u have an idea for why my address might not be included
0x13B6Ef05A7Fc58Cdf162314f3bd19cec760a2Aa4

Solo staking since before the merge, validator running on AllNodes, deposit and withdrawl addresses are same

**Comment by jdgsb** [comment]
@jagmot Thank you for your response. My AllNodes ETH validators were definitely launched months before the merge and all of them have the same withdrawal address. Similar to the comment above, the address I used for AllNodes is not on any of the lists. Happy to take this offline if it is easier. Just want to make sure there isn't any issue for the overall solo staking community.

**Comment by dozer-eth** [comment]
My solo staking addresses on allnodes are also excluded from this list.  They were all staking before/through the merge. 
 Deposit addresses:
0x0FD4A2D2cD0fC2A9a5df08538f8Ae7c0cB464329
0xd17d437e814b3A624788A92Dc848C76F8f83445a
0x28681A153ea0a69E2FAf3736805a11153FD71A97
0xf7f73a12533C2c0b2269101242B2Aa6D9459BB5e
0x171bB6833e0441479AF6b8f8F08040E0aD591cc1

**Comment by jagmot** [comment]
> @jagmot Thank you for your response. My AllNodes ETH validators were definitely launched months before the merge and all of them have the same withdrawal address. Similar to the comment above, the address I used for AllNodes is not on any of the lists. Happy to take this offline if it is easier. Just want to make sure there isn't any issue for the overall solo staking community.

Please feel free to send me your address on the Allnodes.com chat (bottom right-hand corner and I can check). Please make sure you followed my earlier instructions about clicking on Ethereum when checking provisions website

**Comment by jagmot** [comment]
0x13B6Ef05A7Fc58Cdf162314f3bd19cec760a2Aa4

naman14, I checked your address above and it has been qualified. You need to make sure that you click Ethereum when checking the provisions claim site.

"Congratulations!

This Ethereum wallet address is eligible for Provisions

The Starknet Foundation
is in touch with your organization.

If you are here, it means you have been labelled by Rated Network as a node operator, staking pool provider, or a centralized exchange staker. As such, you are eligible to receive more than one million STRK, to be distributed further to your individual stakers. The Starknet Foundation will be in touch with someone from your organization."

**Comment by jagmot** [comment]
> My solo staking addresses on allnodes are also excluded from this list. They were all staking before/through the merge. Deposit addresses: 0x0FD4A2D2cD0fC2A9a5df08538f8Ae7c0cB464329 0xd17d437e814b3A624788A92Dc848C76F8f83445a 0x28681A153ea0a69E2FAf3736805a11153FD71A97 0xf7f73a12533C2c0b2269101242B2Aa6D9459BB5e 0x171bB6833e0441479AF6b8f8F08040E0aD591cc1

I checked all of your addresses, and they all qualify. Perhaps it has been resolved since you first posted, or you need to click Ethereum on the provisions.starknet.io website.

"Congratulations!

This Ethereum wallet address is eligible for Provisions

The Starknet Foundation
is in touch with your organization.

If you are here, it means you have been labelled by Rated Network as a node operator, staking pool provider, or a centralized exchange staker. As such, you are eligible to receive more than one million STRK, to be distributed further to your individual stakers. The Starknet Foundation will be in touch with someone from your organization."

**Comment by magicmurph** [comment]
I am in the same situation.
![Uploading PXL_20240220_154941139.jpg…]()

Solo staking on all nodes.  Am eligible but says to get in contact with organization. 

0xbd0E8Fc3d1A704BC66e759903040F07Bae161dd3

**Comment by magicmurph** [comment]
Issue not resoloved.  I staked using Allnodes hardware only.  I still configured, and sent ETH to the beacon chain.  Held the private seed the whole time.  I only rented the hardware.
