### ISSUE TITLE
Validators not included

### ISSUE THREAD

**Issue by mayfieldtom** [rated-network/solo-stakers#80]
Hi,
I am a solo-staker since genesis with currently 50 validators.
None of these are in csv file. 

Deposit addresses:
0xd808479Aa4c53792eA6f7BD0aD42812DAd7F5EA1
0x02E8D0891a72c5aeCB6741ea011A6c56925bc40d
0x9a6357A4fc4c27D9f91CC98d95130658B8F30d89

Withdrawal address for all validators: 0x696F4919D80055E91b52bFBF1E580FB7C627fB01

The 10 pre-merge validators: 11696,64599,110042,110044,110045,233353,345018,345019,345020,345021
Other 40: 436733,436734,436735,436736,436737,437624,437625,437626,437627,437634,440706,440707,440708,440709,440710,440712,440713,440714,440715,440716,728330,728379,728380,728381,728382,728383,728384,728385,728386,728387,735836,735837,735838,735840,735841,735842,735843,735845,735849,735850

**Comment by ariskk** [comment]
Thanks for reporting. We will look into it.

**Comment by ariskk** [comment]
You are here 
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L7517
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5439
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L3752
