### ISSUE TITLE
Solo staker since the first month of the beacon chain, got classified as a pool

### ISSUE THREAD

**Issue by bulrathiking** [rated-network/solo-stakers#82]
Deposit address: 0x6045B5248408FFA09D27A5077fB88dDa1dc8A73a
Withdraw address: 0xE126e752FeDf0a03312dB7c4Db2f8C5B5D8dEADB

Validator: https://beaconcha.in/validator/70028

I've been operating this validator since January 2021, having entered the queue on January 5, 2021. It functions as a self-custodial validator, where I am the sole owner of the withdrawal keys. I rely on the allnodes service to avoid dealing with the complications of power outages, while still maintaining ultimate control over the validator, specifically the withdrawal keys (as well as the validator keys). I believe instances like mine are essential for Ethereum, as they represent decentralized control over staked funds, contrasting with the concentration of ETH in a few corporations susceptible to negative behavior and external pressures. If validators like mine are not treated differently from those in platforms like Lido, it raises questions about the motivation to continue such an independent setup. Why not simply stake with Lido, participate in airdrops on Eigen layer, and so forth? Is this the direction we want for the Ethereum ecosystem?
Please fix this, for the sake of the network

**Comment by ariskk** [comment]
Hi, it's not up to us to decide how cases like yours are treated, and I totally agree with you that self-custody is important. 

According to our definition of solo stakers, non-custodial staking providers are excluded from this list. That said, we have provided the full list (solo and non-solo stakers) and it is up to the downstream consumer (in this case Starknet) to decide how to distribute to each category.
