### ISSUE TITLE
Pre-genesis solo staker identified as pool

### ISSUE THREAD

**Issue by someone202302** [rated-network/solo-stakers#85]
Hi,

I'm a solo staker at home with 15 validators pre-genesis and 5 post.

- Deposit address: 0xe8f7504d63290dA703b30ccC38fE47b0e9dc6F55
- Withdrawal address: 0xb64e2D92b22d6F3ce8346a8E4b2EbE896aC65dAd
- Validator indices (pre-genesis): 6210, 6211, 6212, 6213, 6214, 6215, 6216, 6217, 6218, 6219, 6220, 6221, 6222, 6223, 6224
- Validator indices (post): 403572, 403573, 577573, 577574, 577582

Can you please classify me as a solo staker?

Thanks in advance.

**Comment by ariskk** [comment]
Thanks for reporting. We will look into it.

**Comment by ariskk** [comment]
It's here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L5949
