### ISSUE TITLE
Solo Staker Validator Index 23113 Omitted

### ISSUE THREAD

**Issue by jeshli** [rated-network/solo-stakers#86]
Validator Index: 23113
Public Key: 0xa9e294a14238d2a327cb9ee7c3b7354217506d6e3846b7f9d05b2fe4cdef2adb462eac66691a62423910829fe9ce2f92

Pre-Genesis Deposit
Early Validator
Solo Home Set Up

**Comment by ariskk** [comment]
Hi, this validator is on the list https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v0.csv#L6356

Note: being on the list doesn't guarantee anything wrt the ongoing airdrop. Starknet have applied their own criteria on top.
