### ISSUE TITLE
Question in regards to Rated’s “solo-staker filter” list - Active vs Exited validators

### ISSUE THREAD

**Issue by ethSoloStaker** [rated-network/solo-stakers#88]
I hope it is OK to ask a question via the "issues" section.

The questions being, does the Rated’s “solo-staker filter” take into account whether the status of the validator is taken into account? I.e. Active vs Exited.

As something that is constantly changing, I would assume not, and all "solo-stakers" current and past are included in your list. 

If this is not taken into account, I could see a future where validators are set up, operated for a short period, then exited and cycled through again and again to create a large number of "solo-stakers" for farming future air drops.

I also understand you are just providing the list and users, and it is up to projects as to how they use it. So potentially it would be up to the project to decide if then run the list through an "is active?" filter when allocating/provisioning tokens.

It would be interesting to hear if this has been considered or discussed.

**Comment by ariskk** [comment]
To produce a version of the list we use features derived from validator operating performance. To be able to create those, a validator has to be active in the window of time we analyse. Thus, inactive ones are excluded. This doesn't prevent a downstream app from using an older version of the list obviously.

This is a very interesting point you bring up. Thanks you. I suspect the solution is for people to use the latest version of the list and filter for active validators to avoid running into this issue. We can always help with that, but obviously now that the list is out in the open people can use it as they see it so the results will be unpredictable.
