### ISSUE TITLE
Multiple Solo Staker Validators not Included 

### ISSUE THREAD

**Issue by ethstaker88** [rated-network/solo-stakers#91]
Here is the Deposit address for the validators:

0xEa552377042A48e5635C8116D0AE201514ebA2BD

No Withdrawal address is currently set.

**Comment by ariskk** [comment]
Having no withdrawal address almost a year after Shapella is a very strong signal we didn't have when we first conducted this research and we will use in the next version.

Thanks for reporting.

**Comment by ariskk** [comment]
Here https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v1.csv#L7572
