### ISSUE TITLE
ETH balance miscalculated 

### ISSUE THREAD

**Issue by KX92** [rated-network/solo-stakers#92]
Hi, my Eth balance at 15 novembre was incorrect calculated. l want to contest the result of Starknet airdrop for wallet:
0x02944fe7C39B1dcb3aD65Cf447209AA462C2711f4fc3F86E96889dDD342aBcfd
Thanks!
![15 11 2023](https://github.com/rated-network/solo-stakers/assets/124437439/d89489c2-3d51-4d82-af87-981731d2fc03)

**Comment by ariskk** [comment]
Hi! Unfortunately this repo only deals with solo staker addresses. For anything else please reach out to Starknet directly.

**Comment by KX92** [comment]
ok, thanks
