### ISSUE TITLE
Full list of solo stakers withdrawals (85)

### ISSUE THREAD

**Issue by Infer114** [rated-network/solo-stakers#94]
Hello,

I made a compilation of all withdrawals I found in both rated network and starknet provision's githubs.
I literally picked all withdrawals addresses I found (85), and some times more deeply if only validator index was posted, so some should miss.
If it's missing, please just post your, but remember this must be only before the merge.
Of course there is not anything related to validators who didn't changed their 0x00 credentials, since the criteria is based on this data.
And of course I can't guarantee all are solo stakers, but with this list I think it should be easy to find it (addresses activities, grafiti, etc...), and create a v0.1 csv for rated networks, which could be used at the end by starknet provisions. 

I also posted this in Starknet's provision github : 
https://github.com/starknet-io/provisions-data/issues/29

Hope it helps, even for the future for rated networks !

Full list without duplicates (85) :
0x00000000dDCB8dd8b4a04E11888E7124Ab6EA43D
0x0D319058F592158483062D48152bd84e9a2e7CFE
0x0FC3512F7c6bd54a69eD86578dF0EfdD0F578ab5
0x13B6Ef05A7Fc58Cdf162314f3bd19cec760a2Aa4
0x170CCF19d1FE9F1C360A2Ef0e54983F037bB0034
0x1AAB74A039D7Ff00601B6FE1Bbf13A576521AC83
0x1DD1FCddfAcdA5f3681Dc99c097D67537F0e6816
0x273f4113CCba8aAf856E9ec852346F475797Ee58
0x2A84dC7f347CeaF5Ca48745aA6DfC8ac4B938Fe9
0x2c537ac6209b5E392207783DF4671fdb932aFf44
0x2CAf9E690b9B33FD1EC6DfcA52AD4eB628ee401b
0x2f4c3929C68739AF7a4d87aB309d871e7D58A2d8
0x3319650ca8F53e1F7597d761aB75B64453FAcf53
0x35873Ac2B1aD6c584AFB13a2ad752B230FD2bEEF
0x372d29C978f9Fb10c28563557dbb65b61a08aE49
0x38c02f9b1fa8c729574e28e1d2e98a7b76d69f82
0x38d11B3E1a5cB0e7C3381b9c682cBce541020BCf
0x3e9040303E9A1983AD99e0AE2263c92e3E542eB9
0x40d02eAFc7f241cb870E0f07aeB12E23b817fCe5
0x412B01c1E79c8e93e3b2739cBD7B3D97a30d6B5B
0x41374B389772D5aEd41240a57f5FFB087C6bfA93
0x4231B2f83CB7C833Db84ceC0cEAAa9959f051374
0x42751916BD8e4ef1966ca033D4EA1FA2a8563f88
0x42894ac70142754bf9e3f3c191a12eeb05E2910d
0x42a63047a1cD8449e3E70aDEB7363C4Ca01DB528
0x434B2a7d39CE1BB5bf4d7d04B9A1D004d7a494BF
0x473D13919ebd47E73BE21B0a3B4982ce09961F78
0x47476Eee389Ab9bc767E9603812175C9DaB5737E
0x4bded2846e50bbcd49bf31ac066ff5cf94902316
0x4F13D70f72292E699fbB420003CafF2778c18f70
0x51De21beC7F334cDC01d3787e2a150216628E021
0x54E3110c567FfBa372E705Dee13e03BF5fFD66E8
0x5C649840490218D6C4481C3B49F9d39756CDAf3C
0x5f055f332C4A5bA920D934Ff69CD1Bf747eCe5b9
0x62d164ec972c048e0c9c4fa26e6c3b9984982d25
0x68b8A6aDA2749C4E280eC6Aca1252BF64427Ed48
0x696F4919D80055E91b52bFBF1E580FB7C627fB01
0x6d8538AF46c6D355Ea461aA7AAC2E7B01e8A067d
0x6e9011B8Dfe86e2Ae8a886D432E4A4c78c85648E
0x727D03Ac9A961c830d95914C9213bDa3f336472C
0x751fa5Fc8B96454B0CCA47d640E1d79e42624c14
0x774F45a32cA6A365B693Dfd58d129c959fC159D9
0x797e2ea686D5d1c71da6ee240BDe1e49D6B642Cb
0x7CA545eBc6153765330F37749E1c1A362F63f05e
0x801eE277a12C382f3b1C3613486A17ae4a981254
0x8a60a233F03B2E78889031efA9B4c4aDA6aA4c7d
0x8Ae16d842A853365E6a1EE7eD2A0c80b8fE298aC
0x8B021A0D0e113746c79f0eF8c396aDE292Ec9030
0x8d43bc364F8bD4aFD491cB27FDC738C44F9CC393
0x92ed4b99c68A607D2D0571a8f2c1D4b6EaB01E1d
0x93bfa1be799eedf037c371d6e493dbd242d810e2
0x9768339588DD531096222A99c4d258d646b76a80
0x9897B34B6C11d2a55af9cE886Fb927b39c69392F
0x9BB3072DDC08C1f29F5e036299EEd8D3c6ad3853
0x9E12Ab4646D97bc33d156D795Ab64C50984eF7cb
0x9F8a1EA3C131B8F837E03FE8f8722A02e688c88C
0xa43C3FA89a6ff585f324D848C198E3641dF6e873
0xacC7B5FD421580D45dD63d42A4a6b5AF796822ac
0xAd7e8C174AB48BB86D7EBEEEc5Ed3fC0e27528e0
0xB154AF72c7f5760a92C46193Aeb24FF8DDd64488
0xB4B65FCb010ce087E4B90eA73D9b313C93fC352D
0xB54b2fa88707a910E7B6E282006AB02f18250ae6
0xb5aD6DaC39528972f4E01169e798F00345676cC6
0xb64e2D92b22d6F3ce8346a8E4b2EbE896aC65dAd
0xbC5a4A09450B4106bE9a4DF3d85dA3F4617e819F
0xbd0E8Fc3d1A704BC66e759903040F07Bae161dd3
0xBE8859cA9C3B0AA3B55644B9fD90017512A80801
0xC0567a6fe0f3083603D639c8233024E8bD1926d6
0xc4374C15b5d3e0f43125CC944Abf5D1411a4a0db
0xC7759520AF30524eDc1dE0785a3e72Dd3FbfDC32
0xC895A0F3D3D0D4F226934D756252e07Af90fD45d
0xcfc7e96be27d836b034b37132052549611341108
0xd4df2ba7e0b056a3b323c6f2ef037286e7410734
0xE126e752FeDf0a03312dB7c4Db2f8C5B5D8dEADB
0xE2EFFFfE7fB7015862cBb1958A30967e48030cFF
0xe75AFa985de4F013AccFc8b4Dd744551C6EEB5a9
0xe8637bB8ACf92391140bFb6570AAfCdbe20e70A1
0xEba0E1FbC9Ac1675c62D53EF0320f95F5BD33cca
0xEE48671f1E55BEF74103b5C496E861c18Ee71dad
0xf2125d80AFF9078c163fb9d293f91E21d2A0095C
0xF3523fd7318C8Fb037eD081cDb478d45C70eD570
0xF414cbdA083303E288D356FBdE34f70bD82B9930
0xfa42dC95E344f976d4B043Ca227c474470B670DC
0xFA5f9EAa65FFb2A75de092eB7f3fc84FC86B5b18
0xfE7dEeADf7a9D02fb743A9354e17022ECA21b193

What I used for doing it :

provisions-data, issues 27 to 1, 17/02/2024 10am Paris Timezone : 

27-
0x0FC3512F7c6bd54a69eD86578dF0EfdD0F578ab5
0x68b8A6aDA2749C4E280eC6Aca1252BF64427Ed48
26-
0x9BB3072DDC08C1f29F5e036299EEd8D3c6ad3853
0x801eE277a12C382f3b1C3613486A17ae4a981254
0xbC5a4A09450B4106bE9a4DF3d85dA3F4617e819F
23-
0x8d43bc364F8bD4aFD491cB27FDC738C44F9CC393
0x8Ae16d842A853365E6a1EE7eD2A0c80b8fE298aC
0x2f4c3929C68739AF7a4d87aB309d871e7D58A2d8
22-
0xa43C3FA89a6ff585f324D848C198E3641dF6e873
20-
0x7CA545eBc6153765330F37749E1c1A362F63f05e
18-
0x2CAf9E690b9B33FD1EC6DfcA52AD4eB628ee401b
17-
0x774F45a32cA6A365B693Dfd58d129c959fC159D9
15-
0x9768339588DD531096222A99c4d258d646b76a80
14-
withdrawal credentials still at 0x00, imo it's an other subject here
9-
0xfa42dC95E344f976d4B043Ca227c474470B670DC
0x42751916BD8e4ef1966ca033D4EA1FA2a8563f88
0xe8637bB8ACf92391140bFb6570AAfCdbe20e70A1
0x42894ac70142754bf9e3f3c191a12eeb05E2910d
0x6d8538AF46c6D355Ea461aA7AAC2E7B01e8A067d
0x9897B34B6C11d2a55af9cE886Fb927b39c69392F
0x412B01c1E79c8e93e3b2739cBD7B3D97a30d6B5B
0xF3523fd7318C8Fb037eD081cDb478d45C70eD570
0x4231B2f83CB7C833Db84ceC0cEAAa9959f051374
0xF414cbdA083303E288D356FBdE34f70bD82B9930
0x92ed4b99c68A607D2D0571a8f2c1D4b6EaB01E1d
0x170CCF19d1FE9F1C360A2Ef0e54983F037bB0034
0x774F45a32cA6A365B693Dfd58d129c959fC159D9 (duplicate with issue 17)
0x6e9011B8Dfe86e2Ae8a886D432E4A4c78c85648E
0xC895A0F3D3D0D4F226934D756252e07Af90fD45d
0x1DD1FCddfAcdA5f3681Dc99c097D67537F0e6816
0xacC7B5FD421580D45dD63d42A4a6b5AF796822ac
0xb64e2D92b22d6F3ce8346a8E4b2EbE896aC65dAd
0x38d11B3E1a5cB0e7C3381b9c682cBce541020BCf
0x0D319058F592158483062D48152bd84e9a2e7CFE
0xcfc7e96be27d836b034b37132052549611341108
0x54E3110c567FfBa372E705Dee13e03BF5fFD66E8
0x4F13D70f72292E699fbB420003CafF2778c18f70
0xfE7dEeADf7a9D02fb743A9354e17022ECA21b193
0x51De21beC7F334cDC01d3787e2a150216628E021
0x727D03Ac9A961c830d95914C9213bDa3f336472C
0x4bded2846e50bbcd49bf31ac066ff5cf94902316
0x62d164ec972c048e0c9c4fa26e6c3b9984982d25

rated network, issues 1 to 87, 17/02/2024 10.30am Paris Timezone : 

3-
0xc4374C15b5d3e0f43125CC944Abf5D1411a4a0db
0xAd7e8C174AB48BB86D7EBEEEc5Ed3fC0e27528e0
0xB4B65FCb010ce087E4B90eA73D9b313C93fC352D
0xE2EFFFfE7fB7015862cBb1958A30967e48030cFF
0xF3523fd7318C8Fb037eD081cDb478d45C70eD570
0xe8637bB8ACf92391140bFb6570AAfCdbe20e70A1
6-
0x372d29C978f9Fb10c28563557dbb65b61a08aE49
7-
0x5C649840490218D6C4481C3B49F9d39756CDAf3C
8-
0x13B6Ef05A7Fc58Cdf162314f3bd19cec760a2Aa4
9-
0x93bfa1be799eedf037c371d6e493dbd242d810e2
10-
0xB154AF72c7f5760a92C46193Aeb24FF8DDd64488
0x3e9040303E9A1983AD99e0AE2263c92e3E542eB9
0x273f4113CCba8aAf856E9ec852346F475797Ee58
0xEba0E1FbC9Ac1675c62D53EF0320f95F5BD33cca
11-
0xFA5f9EAa65FFb2A75de092eB7f3fc84FC86B5b18
13-
0x00000000dDCB8dd8b4a04E11888E7124Ab6EA43D
14-
0x434B2a7d39CE1BB5bf4d7d04B9A1D004d7a494BF
16-
0xE2EFFFfE7fB7015862cBb1958A30967e48030cFF (duplicate issue 3)
17-
0x7CA545eBc6153765330F37749E1c1A362F63f05e
20-
0xB154AF72c7f5760a92C46193Aeb24FF8DDd64488 (duplicate issue 10)
22-
0xB54b2fa88707a910E7B6E282006AB02f18250ae6
25-
0xbd0E8Fc3d1A704BC66e759903040F07Bae161dd3
26-
0x3319650ca8F53e1F7597d761aB75B64453FAcf53
27-
0x6d8538AF46c6D355Ea461aA7AAC2E7B01e8A067d
0x9897B34B6C11d2a55af9cE886Fb927b39c69392F
29-
0x412B01c1E79c8e93e3b2739cBD7B3D97a30d6B5B
32-
0x473D13919ebd47E73BE21B0a3B4982ce09961F78
33-
0xF3523fd7318C8Fb037eD081cDb478d45C70eD570 (duplicate issue 3)
34-
0xfa42dC95E344f976d4B043Ca227c474470B670DC
35-
0xb5aD6DaC39528972f4E01169e798F00345676cC6
36-
0x5f055f332C4A5bA920D934Ff69CD1Bf747eCe5b9
38-
0xAd7e8C174AB48BB86D7EBEEEc5Ed3fC0e27528e0 (duplicate issue 3)
40-
0x4231B2f83CB7C833Db84ceC0cEAAa9959f051374
41-
0x47476Eee389Ab9bc767E9603812175C9DaB5737E
47-
0x8a60a233F03B2E78889031efA9B4c4aDA6aA4c7d
48-
0x9768339588DD531096222A99c4d258d646b76a80
49-
0x774F45a32cA6A365B693Dfd58d129c959fC159D9
50-
0x6e9011B8Dfe86e2Ae8a886D432E4A4c78c85648E
51-
0xf2125d80AFF9078c163fb9d293f91E21d2A0095C
52-
0x40d02eAFc7f241cb870E0f07aeB12E23b817fCe5
54-
0x35873Ac2B1aD6c584AFB13a2ad752B230FD2bEEF
55-
0xC895A0F3D3D0D4F226934D756252e07Af90fD45d
57-
0xacC7B5FD421580D45dD63d42A4a6b5AF796822ac
58-
0xe75AFa985de4F013AccFc8b4Dd744551C6EEB5a9
59-
0x2c537ac6209b5E392207783DF4671fdb932aFf44
60-
0xBE8859cA9C3B0AA3B55644B9fD90017512A80801
62-
0xC7759520AF30524eDc1dE0785a3e72Dd3FbfDC32
63-
0x9E12Ab4646D97bc33d156D795Ab64C50984eF7cb
64-
0x797e2ea686D5d1c71da6ee240BDe1e49D6B642Cb
67-
0x8B021A0D0e113746c79f0eF8c396aDE292Ec9030
68-
0x42a63047a1cD8449e3E70aDEB7363C4Ca01DB528
0x751fa5Fc8B96454B0CCA47d640E1d79e42624c14
71-
0xbd0E8Fc3d1A704BC66e759903040F07Bae161dd3 (duplicate issue 25)
72-
0x8d43bc364F8bD4aFD491cB27FDC738C44F9CC393
0x8Ae16d842A853365E6a1EE7eD2A0c80b8fE298aC
0x2f4c3929C68739AF7a4d87aB309d871e7D58A2d8
73-
0x38c02f9b1fa8c729574e28e1d2e98a7b76d69f82
74-
0x9F8a1EA3C131B8F837E03FE8f8722A02e688c88C
75-
0x0D319058F592158483062D48152bd84e9a2e7CFE
76-
0xd4df2ba7e0b056a3b323c6f2ef037286e7410734
77-
0xC0567a6fe0f3083603D639c8233024E8bD1926d6
78-
0xEE48671f1E55BEF74103b5C496E861c18Ee71dad
80-
0x696F4919D80055E91b52bFBF1E580FB7C627fB01
81-
0x4F13D70f72292E699fbB420003CafF2778c18f70
82-
0xE126e752FeDf0a03312dB7c4Db2f8C5B5D8dEADB
83-
0x1AAB74A039D7Ff00601B6FE1Bbf13A576521AC83
84-
0x2A84dC7f347CeaF5Ca48745aA6DfC8ac4B938Fe9
85-
0xb64e2D92b22d6F3ce8346a8E4b2EbE896aC65dAd
86-
0x41374B389772D5aEd41240a57f5FFB087C6bfA93
87-
0xfE7dEeADf7a9D02fb743A9354e17022ECA21b193

**Comment by ProSoloStaker** [comment]
Hi @ariskk, thank you and your team for the great work. 

The list above looks quite comprehensive based on issues raised so far. Missing solo stakers would be really grateful if you could kindly prioritize this for next release. 

I understand that there is no guarantee on timing for next update. We are hoping for some adjustments soon as Abdel from Starknet suggested that timing might be an issue, as coming claim is around the corner.

In any case very grateful for your work. Thanks.

**Comment by ariskk** [comment]
Hi folks. The updated address is live. A number of addresses above (~55-ish I think) are on the updated list. Some of them are not as they didn't meet the criteria we set for solo stakers in the original research. 
Thank you for putting this together, it was quite helpful.

**Comment by Infer114** [comment]
thanks for checking it @ariskk ;)

**Comment by kernelwhisperer** [comment]
> Hi folks. The updated address is live. A number of addresses above (~55-ish I think) are on the updated list. Some of them are not as they didn't meet the criteria we set for solo stakers in the original research. Thank you for putting this together, it was quite helpful.

@ariskk can you elaborate on the criteria?

The only thing I found was this excerpt:

> After some experimentation we found 90 days as the determined time window worked well. It allowed for enough time for patterns in behaviour to emerge. To ensure that examined validators were active throughout the selected window, only validators activated prior to 27/11/2022 were used. The total number of validators in this set is 500,000.

I can confirm that my validator 12853 has been activated prior 27/11/2022.
