### ISSUE TITLE
Missing solo staker

### ISSUE THREAD

**Issue by solonodemissing** [rated-network/solo-stakers#95]
This address is also missing from the solo list. It was also a solo staking validator in the given period. Please check. Thanks.

Deposit address: 
0x26c541f5e1C8eab0f6F0943Bb1C8843Ab18C4B0D

Withdrawal address:
0x01000000000000000000000026c541f5e1c8eab0f6f0943bb1c8843ab18c4b0d

**Comment by ariskk** [comment]
The validators in this address have been reported to us by a non-custodial staking provider. We may in the future provide a list of those addresses separately.
