### ISSUE TITLE
genesis validator missing on list

### ISSUE THREAD

**Issue by kriegb** [rated-network/solo-stakers#96]
there are 7 validator that stake since genesis: `7418, 7419, 7420, 7421, 7422, 7423, 7424`
with deposit address: `0xbbc9A3dAA1e5A038B1F88f8DF859681c6533D631`
and withdrawal address: `0x727D03Ac9A961c830d95914C9213bDa3f336472C`

my current analysis as for why it is not included, because I am using my withdrawal address to spin up one new validator after the merge, maybe rated network flag my deposit and withdrawal address respectively as depositor with 7 validator and 1 validator and thus making the 7 validator does not have a withdrawal address although on chain it is clearly that the withdrawal address already set.

**Comment by ariskk** [comment]
You are pretty high up on the list and as far as I can see your withdrawal creds are set. Unfortunately we just provided the list, there were various post-processing steps the foundation implemented that are outside of our control. I would suggest to reach out to them directly.
