### ISSUE TITLE
10 validators but only 6k STRK

### ISSUE THREAD

**Issue by Rainingeth** [rated-network/solo-stakers#99]
Similar issue as many others...

Withdrawal Address is 0x8A59E5142B60150C1831f24E297295A14c40d680

Validators: 45677, 178565, 178745, 178746, 179589, 179590, 183618, 183619, 184144, 184145

Thank you

**Comment by ariskk** [comment]
You are on the list, eg
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v0.csv#L5587
https://github.com/rated-network/solo-stakers/blob/main/solo_stakers_v0.csv#L6113

We were not involved in the distribution process, so we can't advise on how exactly those allocations were calculated. I would suggest to reach out the foundation directly.
